spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/x
    username: xuexingdong
    password: 123456
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    username: guest
    password: guest
    publisher-confirms: true
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8090

wechat:
  appid: wxee0ca058e61580f3
  appsecret: 090de7f06fc16808627e1fa3b1218163
  token: xxd
  encrypt-mode: CLEAR