spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: 300ms
        max-idle: 50
        min-idle: 10
    timeout: 0ms
  rabbitmq:
    username: guest
    password: guest
    publisher-confirms: true
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8090

wechat:
  appid: wxee0ca058e61580f3
  appsecret: 090de7f06fc16808627e1fa3b1218163
  token: xxd
  encrypt-mode: CLEAR

logging:
  level: debug

