spring:
  application:
    name: backend
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    basename: i18n/messages/messages
mybatis:
  mapper-locations: classpath:com/xuexingdong/x/mapper/*Mapper.xml
  type-aliases-package: com.xxd.x.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  params: count=countSql

server:
  servlet:
    context-path: /api