spring:
  datasource:
    url: jdbc:mysql://localhost/x?useSSL=false
    username: root
    password: 123456
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: x

jwt:
  secret-key: xuexingdong
  expiration: 1d

point:
  register: 50
  create-activity: -100

server:
  port: 8081

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xuexingdong.x: debug
