spring:
  datasource:
    url: jdbc:mysql://localhost/x
    username: root
    password: 123456
  data:
    mongodb:
      database: crawler

server:
  port: 8082

siteurl: 10.0.0.32:9000

logging:
  level:
    com.xuexingdong.x: DEBUG
