spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ucenter?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: msg
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: 300s
        max-idle: 50
        min-idle: 10
    timeout: 0s
    database: 0

server:
  port: 8888

token:
  secret-key: xxd
  expire-time: 0