spring:
  datasource:
    hikari:
      validation-timeout: 60000
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  shutdown: "graceful"