spring:
  application:
    name: auth
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:com/xuexingdong/x/mapper/*Mapper.xml
  type-aliases-package: com.xuexingdong.x.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    context-path: /auth

