spring:
  datasource:
    url: jdbc:mysql://localhost/x?useSSL=false
    username: root
    password: 123456

server:
  port: 8888

jwt:
  secret-key: 0Q20PjZkaJ1SHin0Yu6DULS8fNHJkWXlJa6LNtPSA9paxRVLWB7Xfnlptm5tgxUS
  expiration: 1d

salt: 'I hate the world'