spring:
  application:
    name: backend
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  mapper-locations: classpath:com/xuexingdong/x/mapper/*Mapper.xml
  type-aliases-package: com.xuexingdong.x.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    context-path: /admin
