spring:
  datasource:
    url: jdbc:mysql://localhost:5432/x
    username: xuexingdong
    password: 123456
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: x

jwt:
  secret-key: xuexingdong
  expiration: 1d