spring:
  datasource:
    url: jdbc:mysql://localhost/x?useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: x

jwt:
  secret-key: 0Q20PjZkaJ1SHin0Yu6DULS8fNHJkWXlJa6LNtPSA9paxRVLWB7Xfnlptm5tgxUS
  expiration: 1d

server:
  port: 8081